import type React from "react";

export const leftPanelStyles: Record<string, React.CSSProperties> = {
  panel: {
    background: "#ffffff",
    borderRight: "1px solid #e2e8f0",
    overflowY: "auto",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  patientHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  avatar: {
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontWeight: 700,
    fontSize: "18px",
    flexShrink: 0,
    position: "relative",
  },
  onlineDot: {
    position: "absolute",
    bottom: "2px",
    right: "2px",
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    background: "#22c55e",
    border: "2px solid white",
  },
  urgentBadge: {
    background: "#fef2f2",
    color: "#ef4444",
    border: "1px solid #fecaca",
    borderRadius: "6px",
    padding: "2px 8px",
    fontSize: "11px",
    fontWeight: 600,
    letterSpacing: "0.05em",
  },
  appointmentBanner: {
    background: "#eff6ff",
    borderRadius: "10px",
    padding: "10px 14px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    color: "#1d4ed8",
    fontWeight: 500,
  },
  sectionCard: {
    background: "#f8fafc",
    borderRadius: "12px",
    padding: "14px",
  },
  sectionLabel: {
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "#94a3b8",
    textTransform: "uppercase" as const,
    marginBottom: "10px",
  },
  statGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
  },
  statItem: {
    background: "white",
    borderRadius: "8px",
    padding: "10px",
    border: "1px solid #f1f5f9",
  },
  statLabel: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#94a3b8",
    letterSpacing: "0.06em",
    textTransform: "uppercase" as const,
    marginBottom: "2px",
  },
  statValue: {
    fontSize: "15px",
    fontWeight: 700,
    color: "#1e293b",
  },
  vitalGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
  },
  vitalCard: {
    background: "white",
    borderRadius: "8px",
    padding: "10px",
    border: "1px solid #f1f5f9",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  vitalIcon: {
    width: "28px",
    height: "28px",
    borderRadius: "8px",
    background: "#eff6ff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    flexShrink: 0,
  },
  bulletItem: {
    fontSize: "13px",
    color: "#475569",
    padding: "3px 0",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  allergyTag: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: 500,
    background: "#fef3c7",
    color: "#92400e",
    border: "1px solid #fde68a",
    marginRight: "6px",
    marginBottom: "6px",
  },
};

export const videoStyles: Record<string, React.CSSProperties> = {
  container: {
    position: "relative",
    background: "#0f172a",
    flex: "0 0 380px",
    margin: "16px 16px 0",
    borderRadius: "16px",
    overflow: "hidden",
  },
  remoteVideo: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  localVideo: {
    position: "absolute",
    bottom: "60px",
    right: "12px",
    width: "110px",
    height: "80px",
    borderRadius: "10px",
    objectFit: "cover",
    border: "2px solid rgba(255,255,255,0.3)",
    background: "#1e293b",
  },
  overlay: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "12px",
  },
  topBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  badge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    background: "rgba(0,0,0,0.5)",
    backdropFilter: "blur(8px)",
    borderRadius: "20px",
    padding: "5px 12px",
    color: "white",
    fontSize: "13px",
    fontWeight: 500,
  },
  connectedDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
  },
  expandBtn: {
    background: "rgba(0,0,0,0.5)",
    backdropFilter: "blur(8px)",
    border: "none",
    borderRadius: "8px",
    padding: "6px",
    color: "white",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  controls: {
    display: "flex",
    justifyContent: "center",
    gap: "12px",
    paddingBottom: "4px",
  },
  idleOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
  },
  joinBtn: {
    padding: "12px 32px",
    borderRadius: "12px",
    background: "linear-gradient(135deg, #3b82f6, #2563eb)",
    color: "white",
    border: "none",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: "8px",
    boxShadow: "0 4px 16px rgba(59,130,246,0.4)",
  },
};

export const chatStyles: Record<string, React.CSSProperties> = {
  panel: {
    flex: 1,
    margin: "12px 16px 16px",
    background: "white",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    border: "1px solid #e2e8f0",
  },
  header: {
    padding: "12px 16px",
    borderBottom: "1px solid #f1f5f9",
    fontWeight: 600,
    fontSize: "14px",
    color: "#1e293b",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    padding: "12px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  inputBar: {
    padding: "10px 16px",
    borderTop: "1px solid #f1f5f9",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  input: {
    flex: 1,
    border: "none",
    outline: "none",
    fontSize: "14px",
    color: "#1e293b",
    background: "transparent",
  },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#94a3b8",
    padding: "4px",
    display: "flex",
    alignItems: "center",
    borderRadius: "6px",
  },
  sendBtn: {
    width: "34px",
    height: "34px",
    borderRadius: "50%",
    background: "#3b82f6",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    flexShrink: 0,
  },
};

export const rightPanelStyles: Record<string, React.CSSProperties> = {
  panel: {
    background: "white",
    borderLeft: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    padding: "16px 20px",
    borderBottom: "1px solid #f1f5f9",
  },
  title: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#1e293b",
    marginBottom: "2px",
  },
  subtitle: {
    fontSize: "12px",
    color: "#64748b",
  },
  unsavedBadge: {
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: 600,
    background: "#fff7ed",
    color: "#c2410c",
    border: "1px solid #fed7aa",
  },
  content: {
    flex: 1,
    overflowY: "auto",
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "#94a3b8",
    textTransform: "uppercase" as const,
  },
  textarea: {
    width: "100%",
    border: "1.5px solid #e2e8f0",
    borderRadius: "10px",
    padding: "10px 12px",
    fontSize: "13px",
    color: "#1e293b",
    resize: "none" as const,
    outline: "none",
    fontFamily: "inherit",
    lineHeight: 1.5,
    boxSizing: "border-box" as const,
  },
  prescriptionBox: {
    border: "1.5px solid #e2e8f0",
    borderRadius: "10px",
    padding: "10px 12px",
  },
  uploadZone: {
    border: "2px dashed #e2e8f0",
    borderRadius: "10px",
    padding: "24px",
    textAlign: "center" as const,
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
  },
  saveBtn: {
    width: "100%",
    padding: "11px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, #3b82f6, #2563eb)",
    color: "white",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
    marginTop: "4px",
  },
};

export function ctrlBtnStyle(
  variant: "normal" | "danger" | "active"
): React.CSSProperties {
  return {
    width: "44px",
    height: "44px",
    borderRadius: "50%",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background:
      variant === "danger" || variant === "active"
        ? "#ef4444"
        : "rgba(255,255,255,0.15)",
    color: "white",
    backdropFilter: "blur(8px)",
  };
}

export function messageBubbleStyle(isMine: boolean): React.CSSProperties {
  return {
    maxWidth: "80%",
    padding: "9px 14px",
    borderRadius: isMine ? "16px 16px 4px 16px" : "16px 16px 16px 4px",
    background: isMine ? "#3b82f6" : "#f1f5f9",
    color: isMine ? "white" : "#1e293b",
    fontSize: "14px",
    lineHeight: 1.4,
  };
}

export function messageTimeStyle(isMine: boolean): React.CSSProperties {
  return {
    fontSize: "11px",
    color: isMine ? "rgba(255,255,255,0.7)" : "#94a3b8",
    marginTop: "3px",
    textAlign: isMine ? "right" : "left",
  };
}